/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import dao.DAOCategoria;
import dao.DAOEmpresa;
import javax.swing.JOptionPane;
import uml.Categoria;
import uml.Empresa;

/**
 *
 * @author bob_1
 */
public class CrearEmpreView extends javax.swing.JFrame {

    /**
     * Creates new form CrearEmpreView
     */
    Empresa emp = new Empresa();
    Categoria cate = new Categoria();
    DAOEmpresa daoE = new DAOEmpresa();
    DAOCategoria daoC = new DAOCategoria();

    public CrearEmpreView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.daoC.LlenarCmb(cmbCate_Crem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre_Crem = new javax.swing.JTextField();
        txtContra_Crem = new javax.swing.JTextField();
        txtCorre_Crem = new javax.swing.JTextField();
        cmbCate_Crem = new javax.swing.JComboBox<>();
        btnCon_Crem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcate = new javax.swing.JTextField();
        txtReg_Crem = new javax.swing.JButton();
        txtIdEs_Crem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(765, 465));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("CREAR EMPRESA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));
        getContentPane().add(txtNombre_Crem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 190, -1));
        getContentPane().add(txtContra_Crem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 190, -1));
        getContentPane().add(txtCorre_Crem, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 170, -1));

        cmbCate_Crem.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                cmbCate_CremComponentMoved(evt);
            }
        });
        getContentPane().add(cmbCate_Crem, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 170, -1));

        btnCon_Crem.setText("CONTINUAR");
        btnCon_Crem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCon_CremMouseClicked(evt);
            }
        });
        getContentPane().add(btnCon_Crem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 210, 50));

        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel5.setText("Correo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel6.setText("Categoria:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        txtcate.setText("1");
        getContentPane().add(txtcate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 50, -1));

        txtReg_Crem.setText("REGRESAR");
        txtReg_Crem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReg_CremMouseClicked(evt);
            }
        });
        getContentPane().add(txtReg_Crem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, -1));

        txtIdEs_Crem.setText("1");
        getContentPane().add(txtIdEs_Crem, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCon_CremMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCon_CremMouseClicked
        int idcate = cmbCate_Crem.getItemAt(cmbCate_Crem.getSelectedIndex()).getId_categoria();
        this.emp.setNombre_emp(this.txtNombre_Crem.getText());
        this.emp.setCorreo_emp(this.txtCorre_Crem.getText());
        this.emp.setContrasena_emp(this.txtContra_Crem.getText());
        //this.emp.setIdcategoria_emp(Integer.parseInt(this.txtcate.getText()));
        this.emp.setIdestad_emp(Integer.parseInt(this.txtIdEs_Crem.getText()));
        
        this.emp.setIdcategoria_emp(idcate);
        //this.emp.setIdcategoria_emp(new Categoria(idcate)); 

        if (this.daoE.Insertar(emp)) {
            JOptionPane.showMessageDialog(this, "INSERTADO CON EXITO");
        } else {
            JOptionPane.showMessageDialog(this, "ERROR AL INSERTAR");
        }
    }//GEN-LAST:event_btnCon_CremMouseClicked

    private void txtReg_CremMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReg_CremMouseClicked
        this.setVisible(false);
        new LoginView().setVisible(true);
    }//GEN-LAST:event_txtReg_CremMouseClicked

    private void cmbCate_CremComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmbCate_CremComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCate_CremComponentMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEmpreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEmpreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEmpreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEmpreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEmpreView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCon_Crem;
    private javax.swing.JComboBox<Categoria> cmbCate_Crem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtContra_Crem;
    private javax.swing.JTextField txtCorre_Crem;
    private javax.swing.JTextField txtIdEs_Crem;
    private javax.swing.JTextField txtNombre_Crem;
    private javax.swing.JButton txtReg_Crem;
    private javax.swing.JTextField txtcate;
    // End of variables declaration//GEN-END:variables
}
