/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import dao.DAOGenero;
import dao.DAOProfesion;
import dao.DAOUsuarios;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import uml.Genero;
import uml.Profesion;
import uml.Usuarios;

/**
 *
 * @author bob_1
 */
public class CrearUsuView extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuView
     */
    DAOUsuarios daoU = new DAOUsuarios();
    DAOProfesion daoP = new DAOProfesion();
    DAOGenero daoG = new DAOGenero();

    Usuarios usua = new Usuarios();
    Profesion prof = new Profesion();
    Genero genr = new Genero();

    public CrearUsuView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.daoP.LlenarCmb(cmbProfe_Crus);
        this.daoG.LlenarCmb(cmbGenero_Crus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre_Crus = new javax.swing.JTextField();
        txtEdad_Crus = new javax.swing.JTextField();
        txtContra_Crus = new javax.swing.JTextField();
        txtCorreo_Crus = new javax.swing.JTextField();
        cmbGenero_Crus = new javax.swing.JComboBox<>();
        cmbProfe_Crus = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        txtIdTipo_Crus = new javax.swing.JTextField();
        txtIdEsta_Crus = new javax.swing.JTextField();
        txtgenero = new javax.swing.JTextField();
        txtprofesion = new javax.swing.JTextField();
        btnRegre_Crus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(765, 465));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("CREAR USUARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setText("Edad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setText("Correo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel6.setText("Genero:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jLabel7.setText("Profesion:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));
        getContentPane().add(txtNombre_Crus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 210, -1));

        txtEdad_Crus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdad_CrusActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdad_Crus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 50, -1));
        getContentPane().add(txtContra_Crus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 150, -1));
        getContentPane().add(txtCorreo_Crus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 210, -1));

        getContentPane().add(cmbGenero_Crus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 150, -1));

        getContentPane().add(cmbProfe_Crus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 150, -1));

        btnRegistrar.setText("CONTINUAR");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 220, 50));

        txtIdTipo_Crus.setText("1");
        getContentPane().add(txtIdTipo_Crus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 20, -1));

        txtIdEsta_Crus.setText("1");
        getContentPane().add(txtIdEsta_Crus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 20, -1));

        txtgenero.setText("1");
        getContentPane().add(txtgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 80, -1));

        txtprofesion.setText("1");
        getContentPane().add(txtprofesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 80, -1));

        btnRegre_Crus.setText("REGRESAR");
        btnRegre_Crus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegre_CrusMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegre_Crus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdad_CrusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdad_CrusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdad_CrusActionPerformed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        this.usua.setNombre_usu(this.txtNombre_Crus.getText());
        this.usua.setEdad_usu(Integer.parseInt(txtEdad_Crus.getText()));
        this.usua.setCorreo_usu(this.txtCorreo_Crus.getText());
        this.usua.setContrasena_usu(this.txtContra_Crus.getText());
        this.usua.setGenero_usu(Integer.parseInt(txtgenero.getText()));
        this.usua.setIdprofesion_usu(Integer.parseInt(txtprofesion.getText()));
        this.usua.setIdtipo_usu(Integer.parseInt(txtIdTipo_Crus.getText()));
        this.usua.setIdestado_usu(Integer.parseInt(txtIdEsta_Crus.getText()));

        if (daoU.Insertar(this.usua)) {
            JOptionPane.showMessageDialog(this, "INSERTADO CON EXITO");
            this.setVisible(false);
            new LoginView().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "ERROR AL INSERTAR");
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegre_CrusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegre_CrusMouseClicked
        this.setVisible(false);
        new LoginView().setVisible(true);
    }//GEN-LAST:event_btnRegre_CrusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegre_Crus;
    private javax.swing.JComboBox<String> cmbGenero_Crus;
    private javax.swing.JComboBox<String> cmbProfe_Crus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtContra_Crus;
    private javax.swing.JTextField txtCorreo_Crus;
    private javax.swing.JTextField txtEdad_Crus;
    private javax.swing.JTextField txtIdEsta_Crus;
    private javax.swing.JTextField txtIdTipo_Crus;
    private javax.swing.JTextField txtNombre_Crus;
    private javax.swing.JTextField txtgenero;
    private javax.swing.JTextField txtprofesion;
    // End of variables declaration//GEN-END:variables
}
