package vistas;

import dao.DAOEmpresa;
import dao.DAOGenero;
import dao.DAOProfesion;
import dao.DAOUsuarios;
import javax.swing.JOptionPane;
import uml.Empresa;
import uml.Genero;
import uml.Profesion;
import uml.Usuarios;

/**
 *
 * @author bob_1
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    DAOUsuarios daoU = new DAOUsuarios();
    DAOProfesion daoP = new DAOProfesion();
    DAOGenero daoG = new DAOGenero();
    DAOEmpresa daoE = new DAOEmpresa();

    Usuarios usua = new Usuarios();
    Profesion prof = new Profesion();
    Genero genr = new Genero();
    Empresa emp = new Empresa();

    public LoginView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCorre_log = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIni_log = new javax.swing.JButton();
        btnVeEmp_log = new javax.swing.JButton();
        btnCrUsu_log = new javax.swing.JButton();
        btnCrEmp_log = new javax.swing.JButton();
        jpfContra_log = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(765, 465));
        setPreferredSize(new java.awt.Dimension(765, 465));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("SISTEMA DE VACANTES PROFESIONALES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));
        getContentPane().add(txtCorre_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 260, -1));

        jLabel2.setText("Correo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        btnIni_log.setText("INICIAR SESION");
        btnIni_log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIni_logMouseClicked(evt);
            }
        });
        getContentPane().add(btnIni_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        btnVeEmp_log.setText("<html>VER EMPRESAS<html>");
        btnVeEmp_log.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVeEmp_log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVeEmp_logMouseClicked(evt);
            }
        });
        getContentPane().add(btnVeEmp_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 130, 90));

        btnCrUsu_log.setText("CREAR USUARIO");
        btnCrUsu_log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrUsu_logMouseClicked(evt);
            }
        });
        getContentPane().add(btnCrUsu_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 130, -1));

        btnCrEmp_log.setText("CREAR EMPRESA");
        btnCrEmp_log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrEmp_logMouseClicked(evt);
            }
        });
        getContentPane().add(btnCrEmp_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 130, -1));
        getContentPane().add(jpfContra_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrUsu_logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrUsu_logMouseClicked
        this.setVisible(false);
        new CrearUsuView().setVisible(true);
    }//GEN-LAST:event_btnCrUsu_logMouseClicked

    private void btnCrEmp_logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrEmp_logMouseClicked
        this.setVisible(false);
        new CrearEmpreView().setVisible(true);
    }//GEN-LAST:event_btnCrEmp_logMouseClicked

    private void btnVeEmp_logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeEmp_logMouseClicked
        this.setVisible(false);
        new EmpreAsoView().setVisible(true);
    }//GEN-LAST:event_btnVeEmp_logMouseClicked

    private void btnIni_logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIni_logMouseClicked
        String pass = new String(this.jpfContra_log.getPassword());
        if (!pass.equals("") && !this.txtCorre_log.getText().equals("")) {
            this.usua.setCorreo_usu(this.txtCorre_log.getText());
            this.usua.setContrasena_usu(pass);
            //---------------------------
            this.emp.setCorreo_emp(this.txtCorre_log.getText());
            this.emp.setContrasena_emp(pass);
            //----------------------------
            if (this.txtCorre_log.getText().equals("Admin")) {
                if (this.daoU.Login(this.usua)) {
                    JOptionPane.showMessageDialog(null, "Bienvenido Administrador.");
                } else {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos.");
                }
            } else {
                if (this.daoU.Login(this.usua)) {
                    JOptionPane.showMessageDialog(null, "Bienvenido/a.");
                    this.setVisible(false);
                    new MenuUsuView().setVisible(true);

                } else if (this.daoE.Login(this.emp)) {
                    JOptionPane.showMessageDialog(null, "Empresa Bienvenida.");
                } else {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Datos.");
        }
    }//GEN-LAST:event_btnIni_logMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrEmp_log;
    private javax.swing.JButton btnCrUsu_log;
    private javax.swing.JButton btnIni_log;
    private javax.swing.JButton btnVeEmp_log;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jpfContra_log;
    private javax.swing.JTextField txtCorre_log;
    // End of variables declaration//GEN-END:variables
}
