package vistas;

import dao.DAOProfesion;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uml.Profesion;

/**
 * Nombre de la clase: Credenciales
 * version: 1.0
 * fecha: 4/06/2021
 * Copyright: ITCA-FEPADE
 * @author Ivan Alexander Osorio Tobar 020320
 * @author Jose Roberto Aragón Lopez 022120
 * @author Jonathan Cunza 
 */
public class ProfesionView extends javax.swing.JFrame {

    /**
     * Creates new form ProfesionView
     */
    
    String []columnas = {"ID", "NOMBRE", "DEMANDA"};
 
    DefaultTableModel model = new DefaultTableModel(columnas, 0);
    DAOProfesion daoProf = new DAOProfesion();
    List<Profesion> data = new ArrayList<>();
    ArrayList mListaSalon;
    Profesion prof = new Profesion();
    //String id_salon;
    
    private void Cargar(){
        this.model.setNumRows(0);
        data.clear();
        data = (List<Profesion>) daoProf.Seleccionar();
        Object [] obj = new Object[3];
        for (Profesion fila: data) {
            obj[0] = fila.getId_profesion();
            obj[1] = fila.getNombre_prof();
            obj[2] = fila.getDemanda_prof();
            this.model.addRow(obj);
        }
        this.dgvTabla_profesion.setModel(model);
    }
    
    
    public ProfesionView() {
        initComponents();
        this.setLocationRelativeTo(null);
        Cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgvTabla_profesion = new javax.swing.JTable();
        txtNombre_prof = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo_prof = new javax.swing.JTextField();
        btnEliminar_prof = new javax.swing.JButton();
        btnAgregar_prof = new javax.swing.JButton();
        btnModificar_prof = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 450));
        setPreferredSize(new java.awt.Dimension(550, 450));
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 280, 48, 16);

        dgvTabla_profesion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dgvTabla_profesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvTabla_profesionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dgvTabla_profesion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 90, 450, 130);
        getContentPane().add(txtNombre_prof);
        txtNombre_prof.setBounds(280, 270, 160, 24);

        jLabel2.setText("Codigo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 280, 42, 16);
        getContentPane().add(txtCodigo_prof);
        txtCodigo_prof.setBounds(160, 270, 60, 24);

        btnEliminar_prof.setText("Eliminar");
        btnEliminar_prof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminar_profMouseClicked(evt);
            }
        });
        getContentPane().add(btnEliminar_prof);
        btnEliminar_prof.setBounds(410, 360, 110, 40);

        btnAgregar_prof.setText("Agregar");
        btnAgregar_prof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregar_profMouseClicked(evt);
            }
        });
        getContentPane().add(btnAgregar_prof);
        btnAgregar_prof.setBounds(20, 360, 110, 40);

        btnModificar_prof.setText("Modificar");
        btnModificar_prof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificar_profMouseClicked(evt);
            }
        });
        getContentPane().add(btnModificar_prof);
        btnModificar_prof.setBounds(220, 360, 110, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregar_profMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_profMouseClicked
        this.prof.setNombre_prof(this.txtNombre_prof.getText());
        if (daoProf.Insertar(this.prof)) {
            JOptionPane.showMessageDialog(this, "INSERTADO CON EXITO");
            Cargar();
        }else{
            JOptionPane.showMessageDialog(this, "ERROR AL INSERTAR");
        }
    }//GEN-LAST:event_btnAgregar_profMouseClicked

    private void btnModificar_profMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificar_profMouseClicked
        this.prof.setId_profesion(Integer.parseInt(this.txtCodigo_prof.getText()));
        this.prof.setNombre_prof(this.txtNombre_prof.getText());
        if (daoProf.Modificar(this.prof)) {
            JOptionPane.showMessageDialog(this, "MODIFICADO CON EXITO");
            Cargar();
        }else{
            JOptionPane.showMessageDialog(this, "ERROR AL MODIFICAR");
        }
    }//GEN-LAST:event_btnModificar_profMouseClicked

    private void btnEliminar_profMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar_profMouseClicked
        this.prof.setId_profesion(Integer.parseInt(txtCodigo_prof.getText()));
        if (daoProf.Eliminar(this.prof)) {
            JOptionPane.showMessageDialog(this, "ELIMINADO CON EXITO");
            Cargar();
        }else{
            JOptionPane.showMessageDialog(this, "ERROR AL ELIMINAR");
        }
    }//GEN-LAST:event_btnEliminar_profMouseClicked

    private void dgvTabla_profesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvTabla_profesionMouseClicked
        int cargar = dgvTabla_profesion.rowAtPoint(evt.getPoint());
        txtCodigo_prof.setText(String.valueOf(dgvTabla_profesion.getValueAt(cargar, 0)));
        txtNombre_prof.setText(String.valueOf(dgvTabla_profesion.getValueAt(cargar, 1)));
    }//GEN-LAST:event_dgvTabla_profesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfesionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfesionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfesionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfesionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfesionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar_prof;
    private javax.swing.JButton btnEliminar_prof;
    private javax.swing.JButton btnModificar_prof;
    private javax.swing.JTable dgvTabla_profesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigo_prof;
    private javax.swing.JTextField txtNombre_prof;
    // End of variables declaration//GEN-END:variables
}
